"""Technology names for idempotent tag seeding (same list as Django load_techs)."""

TECH_LIST = [
    "Python",
    "JavaScript",
    "TypeScript",
    "Java",
    "C#",
    "C++",
    "Go",
    "Rust",
    "PHP",
    "Ruby",
    "Swift",
    "Kotlin",
    "Dart",
    "SQL",
    "Shell Script",
    "Django",
    "Flask",
    "FastAPI",
    "Node.js",
    "Express",
    "NestJS",
    "Spring Boot",
    "ASP.NET Core",
    "Laravel",
    "Ruby on Rails",
    "Elixir Phoenix",
    "React",
    "Vue.js",
    "Angular",
    "Next.js",
    "Svelte",
    "Nuxt.js",
    "Remix",
    "Astro",
    "jQuery",
    "Flutter",
    "React Native",
    "Android SDK",
    "iOS (SwiftUI)",
    "Ionic",
    "PostgreSQL",
    "MySQL",
    "MongoDB",
    "Redis",
    "SQLite",
    "Oracle",
    "Microsoft SQL Server",
    "Cassandra",
    "DynamoDB",
    "Firebase",
    "Docker",
    "Kubernetes",
    "AWS",
    "Azure",
    "Google Cloud (GCP)",
    "Terraform",
    "Ansible",
    "Jenkins",
    "GitHub Actions",
    "GitLab CI",
    "Nginx",
    "Prometheus",
    "Grafana",
    "Git",
    "Linux",
    "API REST",
    "GraphQL",
    "WebSockets",
    "Unit Testing",
    "TDD",
    "Clean Code",
    "Microservices",
    "Serverless",
    "OAuth 2.0",
    "JWT",
    "Tailwind CSS",
    "Bootstrap",
    "Sass",
    "Figma",
    "Adobe XD",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "TensorFlow",
    "PyTorch",
    "Keras",
    "Jupyter Notebook",
    "OpenAI API",
    "LangChain",
    "Selenium",
    "Cypress",
    "Playwright",
    "Postman",
    "Swagger",
    "Jira",
    "Scrum",
    "Kanban",
]
